package com.phasmidsoftware.dsaipg.util.general;

import java.lang.reflect.Array;
import java.util.Collection;
import java.util.Random;
import java.util.function.Function;

/**
 * A utility class providing several static methods for various common operations.
 */
public class Utilities {
    /**
     * Copy a Collection into an array of the given component type.
     * <p>
     * The class has to be passed in. Java erases T at runtime, so there is nothing
     * in {@code Collection<T>} to say what kind of array to make.
     * <p>
     * NOTE this used to take the collection alone and use the runtime class of its
     * FIRST element as the component type. That is right only when every element
     * has that exact class, and silently wrong otherwise: a {@code List<Number>}
     * holding 1 and 2.5 produced an {@code Integer[]} and then threw
     * {@code ArrayStoreException} on the Double — in either order, since whichever
     * element came first decided the type. Any collection whose static type is a
     * supertype of its contents was at risk, which is exactly the case
     * {@code Sort.sort} deals in. The old javadoc warned of a ClassCastException
     * "if you inline this"; the real fault was neither a ClassCastException nor
     * anything to do with inlining.
     * <p>
     * An empty collection is fine now. The old version rejected it, because with no
     * first element it had no way to guess.
     *
     * @param ts    a collection of Ts.
     * @param clazz the component type of the resulting array.
     * @param <T>   the underlying type of ts.
     * @return an array T[] of the same length as ts.
     */
    public static <T> T[] asArray(Collection<T> ts, Class<T> clazz) {
        @SuppressWarnings("unchecked") T[] result = (T[]) Array.newInstance(clazz, 0);
        return ts.toArray(result);
    }

    /**
     * Create a string representing a double, with three decimal places.
     *
     * @param x the number to show.
     * @return a String representing the number rounded to three decimal places.
     */
    public static String formatDecimal3Places(double x) {
        double scaleFactor = 1000.0;
        return String.format("%.3f", round(x * scaleFactor) / scaleFactor);
    }

    /**
     * Create a string representing an integer, with commas to separate thousands.
     *
     * @param x the integer.
     * @return a String representing the number with commas.
     */
    public static String formatWholeWithCommas(final int x) {
        return String.format("%,d", x);
    }

    /**
     * Create a string representing an integer, with commas to separate thousands.
     *
     * @param x the integer.
     * @return a String representing the number without commas.
     */
    public static String formatWhole(long x) {
        return String.format("%d", x);
    }

    /**
     * Converts a double value to its integer representation as a string without commas.
     *
     * @param x the double value to be converted.
     * @return a string representation of the rounded integer value of the input.
     */
    public static String asInt(double x) {
        final long i = round(x);
        return formatWhole(i);
    }

    /**
     * Rounds the given double value to the nearest long value using {@code Math.round}.
     *
     * @param x the double value to be rounded.
     * @return the closest long to the argument, with ties rounding up.
     */
    public static long round(double x) {
        return Math.round(x);
    }

    /**
     * Fills an array with random values generated using the supplied function and random object.
     *
     * @param <T>    the type of the elements in the array.
     * @param clazz  the class of the type of elements in the array.
     * @param random the Random object used to generate random values.
     * @param n      the number of elements in the array.
     * @param f      a function that takes a Random object and generates a value of type T.
     * @return an array of type T filled with random values generated by the function.
     */
    public static <T> T[] fillRandomArray(Class<T> clazz, Random random, int n, Function<Random, T> f) {
        @SuppressWarnings("unchecked") T[] result = (T[]) Array.newInstance(clazz, n);
        for (int i = 0; i < n; i++) result[i] = f.apply(random);
        return result;
    }

    /**
     * Method to calculate log to tbe base 2 of n.
     *
     * @param n the number whose log we need.
     * @return lg n.
     */
    public static double lg(double n) {
        return Math.log(n) / Math.log(2);
    }

}
